/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Mundo.Cola;
import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author TOSHIBA
 */
public class Cajero extends javax.swing.JFrame {

    /**
     * Creates new form Cajer
     */
    Cola cola1;
    int numRecibos;
    String colatext = "";
    Color colorAzul=new Color(153, 153, 255);
    DefaultTableModel modelo;
    DefaultTableModel modeloGantt;
    int contadorProcesos;
    
    public Cajero() {
        this.getContentPane().setBackground(colorAzul);
        cola1 = new Cola();
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
        modeloGantt = (DefaultTableModel) jTable2.getModel();
        
    }

    public void llenarTablaVacia(){
        int numProceso=cola1.getNumProc();
        int rafaga=cola1.getRafaga();
        int tLlegada=cola1.getTLlegada();
        int tFinal =cola1.getTFinal();   
        int tRetorno =cola1.getTRetorno();
        int tEspera = cola1.getTEspera();
        modelo.addRow(new Object[]{numProceso,rafaga,tLlegada,tLlegada,tFinal,tRetorno,tEspera});        
        llenarGantt(tLlegada, tEspera, tLlegada, tFinal, numProceso);
     
    }
    public void llenarTabla(){
        int numProceso=cola1.getNumProc();
        int rafaga=cola1.getRafaga();
        int tLlegada=cola1.getTLlegada();        
        int tComienzo = (int) modelo.getValueAt((contadorProcesos-2), 4);
        cola1.setTComienzo(tComienzo);
        int tFinal =cola1.getTFinal();
        int tRetorno =cola1.getTRetorno();
        int tEspera = cola1.getTEspera();
        modelo.addRow(new Object[]{numProceso,rafaga,tLlegada,tComienzo,tFinal,tRetorno,tEspera});           
        llenarGantt(tLlegada, tEspera, tComienzo, tFinal, numProceso);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TABLA DE GESTION DE PROCESOS");

        jButton3.setText("Adicionar Proceso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIAGRAMA DE GANTT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Rafaga", "Tiempo Llegada", "Tiempo Comienzo", "Tiempo final", "Tiempo retorno", "Tiempo espera"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(460, 460, 460))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(509, 509, 509))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(cola1.vacia()== true){
            cola1.insertar((int)(Math.random()*(10-2)+2),contadorProcesos,0);     
            contadorProcesos ++;
            llenarTablaVacia(); 
            
        }else{
            cola1.insertar((int)(Math.random()*(10-2)+2),contadorProcesos,llegadaRandom());     
            contadorProcesos ++;
            llenarTabla();            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    public int llegadaRandom(){
        int tiempoMax=(int)modelo.getValueAt((contadorProcesos-1), 2)+4;
        int tiempoMin=(int)modelo.getValueAt((contadorProcesos-1), 2);
        int tiempo=(int) (Math.random()*(tiempoMax-tiempoMin)+tiempoMin);
              
    return tiempo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void colorear() {
           jTable2.setDefaultRenderer(Object.class, new Mundo.Color());
    }

    private void llenarGantt(int llegada, int espera, int comienzo, int tfinal, int fila) {
        modeloGantt.addRow(new Object[]{});        
        if (modeloGantt.getRowCount()==1){
            for (int i=comienzo;i<=tfinal;i++){
                modeloGantt.addColumn(i);
            }
        }else{
            for (int i=comienzo+1;i<=tfinal;i++){
                modeloGantt.addColumn(i);            
            } 
        }    
        for (int i=llegada;i<=espera+llegada-1;i++){
            modeloGantt.setValueAt(0, fila, i);
            colorear();
        }
        for (int j=comienzo;j<=tfinal-1;j++){
            modeloGantt.setValueAt(1, fila, j);
            colorear();
        } 
         
    }  
     

}; //To change body of generated methods, choose Tools | Templates.
